### PR TITLE
Added best_fit method to Sphere.

### PR DESCRIPTION
**Pull request by martxelo**
Hello @ajhynes7 

I have created a method for fitting a set of points to a sphere with a least squares solver. It follows the same structure as Plane.best_fit(). The docstring also follows the structure of the Plane.best_fit() docstring.

The method checks if the dimension of the points is equal to 3, checks that there are at least 4 points and that the points do not lie on a plane. Calculates the center and the radius of the sphere that minimizes the distance between the points and the sphere.

I have not updated the tests because there is not a test for Plane.best_fit() method.

I have also updated gitignore for ignoring the virtual environment and PyCharm project folderm but maybe you prefer to remove that.

I hope you like it.

Martxelo

### CODE REVIEW

**Comment by ajhynes7** [comment]
Hi @martxelo,

Docker now has a pull rate limit for it's public images, which was causing your build to fail. I've switched back to using tox instead of Docker, and the new code is in the master branch. So if you update your fork with the latest code from my master branch, it should work.

Could you also add some unit tests for the new method? I'm trying to stay at 100% unit test coverage. 

You can add your name under **Contributors** in `AUTHORS.rst` as well

As for the .gitignore, you shouldn't add the virtualenv and Pycharm project because these are specific to your workflow, while other developers have other workflows (such as using VS code). So if everyone put in their own directories to ignore, the file would be unecessarily cluttered. Here's a good [article](https://julien.danjou.info/properly-managing-your-gitignore/) about this.

**Comment by martxelo** [comment]
Thanks for the tip. I will try to do this way.

**Comment by martxelo** [comment]
Hi @ajhynes7 

I think the PR is finished. I have been struggling with the test in the docstrings: [0,0,0] is not equal to [-0,0,0]. Because of that, I first tried to add is_close to _baseSphere, so I could use the point.is_close() method for comparing the centers of the spheres/circles. But it looks like that method calls math.isclose and it gives False even when the values are close:

`
>>> np.isclose(0, 0.0000000000000000000001)
True
>>> math.isclose(0, 0.0000000000000000000001)
False
`
So, when comparing two points it gives False even when they are [0,0,0] and [1e-17, 0.00e+00, -1e-15]. I am not sure why you use math.isclose instead of np.isclose, or for arrays np.allclose. Maybe there is a subtle reason I don't see. I know the parameters atol and rtol can be tunned (probably needed with values close to zero), but I normally prefer the numpy version.

So I end up discarding that option and use np.allclose and np.isclose for comparing the center and the radius of the sphere directly in the tests.

And  there are  several type errors related with _base_array, vector, points and triangle that I prefer not to fix, because it is likely I will make a mistake. 

And finally I would like to explain the method of the best_fit. The equation of a sphere is like:

(x - c1)² + (y - c2)² + (z - c3)² = R²

With R=radius and [c1, c2, c3]=center. If you extend the parenthesis and move some values you have:

2*x*c1 + 2*y*c2 + 2*z*c3 + (c1² + c2² + c3² - R²) = x² + y² + z²

So if you change (c1² + c2² + c3² - R²) for another variable c4, you get a linear system:

2*x*c1 + 2*y*c2 + 2*z*c3 + c4 = x² + y² + z²

So it can be written like:

A*c = b

A = (2*points, 1)
b = (points**2).sum(axis=1)

And you feed the values to the lstsq method. I hope it is clear.

Regards.

Martxelo

**Comment by ajhynes7** [comment]
Hi @martxelo,

The code looks great! Good job.

Yes, a while ago I switched from using `np.isclose` to `math.isclose` because of some issues I had with `np.isclose` (see this [open NumPy issue](https://github.com/numpy/numpy/issues/10161)).

I figured out why you're getting type errors. NumPy just released version 1.20.0, which includes type annotations. This was being installed by tox and causing type errors. I'd like to update scikit-spatial to use 1.20 in the future, so I don't need to use numpy-stubs anymore for type annotations. For now the issue can be fixed by specifying that version 1.19 is required.

I pulled this PR onto my local machine so I could add some commits. I fixed the type issue and used underscores for unused variables (this was caught by Pylance, which I'm using on VS Code). So I'll merge that branch into master instead of this PR.

Thanks for explaining how the method works. I can add that explanation to the docstring, or even better, link to a reference if you have one.

**Comment by martxelo** [comment]
Hi @ajhynes7 

Sorry I forgot to use underscores. Here is the reference: https://jekel.me/2015/Least-Squares-Sphere-Fit/

Regards

**Pull request merged**
